// Runtime enum-like constants to mirror declarations in src/types/index.d.ts
// Use these in places that need values at runtime (e.g., Mongoose enums, logging)

export const UserRole = {
  APPLICANT: 'APPLICANT',
  REVIEWER: 'REVIEWER',
  ADMIN: 'ADMIN',
  SUPERADMIN: 'SUPERADMIN',
} as const;

export const UserStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  DELETED: 'DELETED',
} as const;

export const ApplicationType = {
  PROVIDER: 'PROVIDER',
  PROFESSIONAL: 'PROFESSIONAL',
  ESTABLISHMENT: 'ESTABLISHMENT',
} as const;

export const ApplicationStatus = {
  DRAFT: 'DRAFT',
  PENDING_DOCUMENTS: 'PENDING_DOCUMENTS',
  PENDING: 'PENDING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;

export const LicenseStatus = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  REVOKED: 'REVOKED',
  SUSPENDED: 'SUSPENDED',
} as const;

export const ProfessionalType = {
  LOCAL: 'LOCAL',
  FOREIGN: 'FOREIGN',
} as const;

export const DropdownCategory = {
  SECTOR: 'SECTOR',
  EMPLOYEE_SIZE: 'EMPLOYEE_SIZE',
  PROFESSIONAL_TYPE: 'PROFESSIONAL_TYPE',
  DESIGNATION: 'DESIGNATION',
  ID_TYPE: 'ID_TYPE',
  SERVICE_TYPE: 'SERVICE_TYPE',
} as const;

export const AuditAction = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_UPDATED: 'USER_UPDATED',
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_REACTIVATED: 'USER_REACTIVATED',
  USER_DELETED: 'USER_DELETED',
  APPLICATION_CREATED: 'APPLICATION_CREATED',
  APPLICATION_UPDATED: 'APPLICATION_UPDATED',
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  APPLICATION_REVIEWED: 'APPLICATION_REVIEWED',
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED',
  DOCUMENTS_REQUESTED: 'DOCUMENTS_REQUESTED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  LICENSE_GENERATED: 'LICENSE_GENERATED',
  LICENSE_VERIFIED: 'LICENSE_VERIFIED',
  DROPDOWN_CREATED: 'DROPDOWN_CREATED',
  DROPDOWN_UPDATED: 'DROPDOWN_UPDATED',
} as const;
